<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * Fix the PostgreSQL CHECK constraint on commissions.status.
 *
 * The original migration created the column as enum('pending','paid'),
 * which in PostgreSQL generates a check constraint only allowing those two values.
 * A later migration added 'menunggu' as the default but forgot to update the
 * PostgreSQL constraint — causing a CHECK violation at runtime.
 *
 * This migration drops the old constraint and adds a new one that includes all
 * three valid lifecycle values: menunggu → pending → paid.
 */
return new class extends Migration
{
    public function up(): void
    {
        $driver = DB::getDriverName();

        if ($driver === 'pgsql') {
            // Drop the stale CHECK constraint generated by the original enum() call.
            DB::statement('ALTER TABLE commissions DROP CONSTRAINT IF EXISTS commissions_status_check');

            // Add a corrected CHECK constraint covering all three valid statuses.
            DB::statement("
                ALTER TABLE commissions
                ADD CONSTRAINT commissions_status_check
                CHECK (status IN ('menunggu', 'pending', 'paid'))
            ");

            // Ensure the column default is also correct.
            DB::statement("ALTER TABLE commissions ALTER COLUMN status SET DEFAULT 'menunggu'");
        }
        // MySQL/SQLite: handled by the earlier migration — no action needed here.
    }

    public function down(): void
    {
        $driver = DB::getDriverName();

        if ($driver === 'pgsql') {
            DB::statement('ALTER TABLE commissions DROP CONSTRAINT IF EXISTS commissions_status_check');
            DB::statement("
                ALTER TABLE commissions
                ADD CONSTRAINT commissions_status_check
                CHECK (status IN ('pending', 'paid'))
            ");
            DB::statement("ALTER TABLE commissions ALTER COLUMN status SET DEFAULT 'pending'");
        }
    }
};
