<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * Records every commission payout triggered by a verified transaction.
     *
     * type values (mapped from business flowcharts):
     *   - downline_registration : Triggered by FC1 (new agent registration)
     *       Gen-1 (direct sponsor)  → Rp450,000
     *       Gen-2 (sponsor's upline)→ Rp100,000
     *       Gen-3 (Gen-2's upline)  → Rp100,000
     *   - repeat_order           : Triggered by FC2 (direct sponsor only)
     *       Gen-1 (direct sponsor)  → Rp250,000
     *
     * generation_level: 1, 2, or 3 for new_agent type; always 1 for repeat_order.
     *
     * status values:
     *   - pending : Commission calculated, awaiting disbursement
     *   - paid    : Successfully disbursed to recipient agent
     *
     * recipient_id: FK to agents.id — the upline agent receiving this commission.
     */
    public function up(): void
    {
        Schema::create('commissions', function (Blueprint $table) {
            $table->id();
            $table->foreignId('transaction_id')
                  ->constrained('transactions')
                  ->cascadeOnDelete();
            $table->foreignId('recipient_id')
                  ->constrained('agents')
                  ->cascadeOnDelete();
            $table->decimal('amount', 15, 2)->notNull();
            // 1 = direct sponsor, 2 = Gen-2 upline, 3 = Gen-3 upline.
            $table->unsignedTinyInteger('generation_level')->notNull();
            $table->enum('type', ['downline_registration', 'repeat_order'])->notNull();
            $table->enum('status', ['pending', 'paid'])->notNull()->default('pending');
            $table->timestamp('paid_at')->nullable();
            $table->timestamps();

            // Support payout dashboard: find all pending commissions for one agent.
            $table->index(['recipient_id', 'status']);
            // Audit: retrieve all commission rows generated by a single transaction.
            $table->index('transaction_id');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('commissions');
    }
};
